version: '3.8'
services:
  node-server:
    build:
      dockerfile: './Dockerfile'
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/api-interview-challenge
      - PORT=8000
  graphql-server:
    build:
      dockerfile: './Dockerfile-graphql'
    ports:
      - 4000:4000
    depends_on:
      - node-server
    environment:
      - PROXY_PORT=8000
      - PROXY_HOST=host.docker.internal
      - PORT=4000
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api-interview-challenge
